#ifndef BESTOFNEXP_GLOBAL_H
#define BESTOFNEXP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BESTOFNEXP_LIBRARY)
#  define BESTOFNEXPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BESTOFNEXPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VECTORGRADIENTWITHSWAPEXP_GLOBAL_H
